"""The reusable part of this build: generate a starter pack.yaml for a new
vertical, structurally valid and ready for a domain expert to fill in.

    python -m vertical_prompts.scaffold \\
        --pack-id real_estate \\
        --display-name "Real Estate Transaction Pack" \\
        --description "Disclosure drafting, addendum comparison, and closing checklists for residential transaction coordinators." \\
        --vertical "Real estate / residential transactions" \\
        --command draft_disclosure:"Draft a required disclosure clause" \\
        --command compare_addendum:"Compare an addendum against the base agreement" \\
        --command closing_checklist:"Summarize documents into a closing checklist" \\
        --out packs/real_estate/pack.yaml

The generated file loads cleanly through `pack_spec.load_pack` immediately —
every required field is present — but each command's `instruction_template`,
`arguments`, and `negotiating`-style domain content are placeholders the
pack author must replace with real domain knowledge. A template can hand you
correct *structure*; it cannot hand you domain expertise, and doesn't
pretend to.
"""
from __future__ import annotations

import argparse
import os
from pathlib import Path

import yaml

PLACEHOLDER_ARG = {
    "name": "context",
    "description": "TODO: describe what this argument means and give an example value.",
    "required": True,
}

PLACEHOLDER_INSTRUCTION = (
    "TODO: write the actual task instruction for this command. Reference "
    "{context} (or whatever argument names you declare above) with curly "
    "braces — every placeholder you use here must be declared in 'arguments'."
)


def _parse_command_flag(raw: str) -> dict:
    if ":" not in raw:
        raise SystemExit(f"--command must be 'id:title', got: {raw!r}")
    command_id, title = raw.split(":", 1)
    command_id = command_id.strip()
    title = title.strip()
    return {
        "id": command_id,
        "title": title,
        "description": f"TODO: one sentence describing what /{command_id} does.",
        "approval_mode": "ask_every_time",  # safest default; author should reconsider per command
        "superdocs_tool": "chat_async",
        "arguments": [dict(PLACEHOLDER_ARG)],
        "export": {"format": "docx", "options": {}},
        "instruction_template": PLACEHOLDER_INSTRUCTION,
    }


def build_pack_dict(pack_id: str, display_name: str, description: str, vertical: str, command_flags: list[str]) -> dict:
    if not command_flags:
        raise SystemExit("at least one --command is required")
    return {
        "pack_id": pack_id,
        "display_name": display_name,
        "description": description,
        "vertical": vertical,
        "commands": [_parse_command_flag(c) for c in command_flags],
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="vertical_prompts.scaffold")
    parser.add_argument("--pack-id", required=True)
    parser.add_argument("--display-name", required=True)
    parser.add_argument("--description", required=True)
    parser.add_argument("--vertical", required=True)
    parser.add_argument("--command", action="append", required=True, help="id:title, repeatable")
    parser.add_argument("--out", required=True, help="Output path for the generated pack.yaml")
    args = parser.parse_args(argv)

    pack_dict = build_pack_dict(args.pack_id, args.display_name, args.description, args.vertical, args.command)

    out_path = Path(args.out)
    os.makedirs(out_path.parent, exist_ok=True)
    header = (
        f"# Generated by `python -m vertical_prompts.scaffold` for the '{args.vertical}' vertical.\n"
        "# Every TODO below needs real domain content before this pack is usable —\n"
        "# the scaffold gives you correct structure, not correct instructions.\n"
    )
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(header)
        yaml.safe_dump(pack_dict, f, sort_keys=False, allow_unicode=True, width=100)

    print(f"Wrote {out_path} with {len(pack_dict['commands'])} command stub(s).")
    print("Next: fill in every TODO, then validate with:")
    print(f"  python -m vertical_prompts.validate {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
