"""Structured input types for a residential lease + disclosure pack.

Nothing here talks to the network. This module exists so `rules.py` has typed
facts to test applicability against, `validate.py` has typed data to gate, and
`render.py` has typed data to render.

The split between typed fields and the free-form `disclosure_facts` map is
deliberate. The typed fields are the ones every lease has regardless of
jurisdiction (who, where, how much, how long). The map holds the answers to
whatever a *particular* jurisdiction asks about — bed bug history in California,
sprinklers in New York, prior flooding in Texas. Rules reference facts by name,
so adding a jurisdiction is a YAML change, not a Python change.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from datetime import date
from typing import Any, Optional

#: Returned by `LeasePackRequest.lookup_fact` when a fact was never supplied.
#: Distinct from `None`/`False`, which are real answers ("no, it has not
#: flooded"). The difference matters: an unanswered applicability question is a
#: blocking error, while a definite "no" simply switches a disclosure off.
UNSET = object()


def safe_slug(value: str, fallback: str = "pack") -> str:
    """Make a user-supplied identifier safe to use as a filename component.

    `pack_id` comes from a hand-written YAML file and is used to name every
    output file. Left raw, a value like `../../etc/passwd` or `CA/OAK-1187`
    would write outside the output directory or fail confusingly on Windows.
    Neither is likely to be malicious here — but a lease record is exactly the
    kind of file that gets generated by some other system and fed in, so it is
    treated as untrusted input.

    Everything outside `[A-Za-z0-9._-]` becomes `-`, leading dots are stripped so
    no output can be hidden or traverse upward, and an empty result falls back
    rather than producing a nameless file.
    """
    cleaned = re.sub(r"[^A-Za-z0-9._-]+", "-", str(value)).strip("-.")
    return cleaned[:80] or fallback


@dataclass
class Party:
    name: str
    role: str  # "landlord" | "tenant" | "agent"
    address: str = ""
    email: str = ""
    phone: str = ""


@dataclass
class Property:
    """The physical thing being let. Fields here are the ones that drive
    disclosure applicability in more than one jurisdiction, so they earn a typed
    slot rather than living in `disclosure_facts`."""

    street_address: str
    city: str
    state: str  # two-letter, e.g. "CA" — selects the jurisdiction rule file
    postal_code: str
    unit: str = ""
    year_built: Optional[int] = None
    property_type: str = "apartment"  # apartment | single_family | condo | duplex | mobile_home
    units_in_building: Optional[int] = None
    county: str = ""

    def full_address(self) -> str:
        unit = f", Unit {self.unit}" if self.unit else ""
        return f"{self.street_address}{unit}, {self.city}, {self.state} {self.postal_code}"


@dataclass
class Tenancy:
    """Commercial terms. `security_deposit` and `monthly_rent` are money and are
    never touched by the model — jurisdiction deposit caps are arithmetic done
    in `validate.py`, in Python, from these two numbers."""

    start_date: str  # ISO YYYY-MM-DD
    end_date: str  # ISO YYYY-MM-DD
    monthly_rent: float
    security_deposit: float
    rent_due_day: int = 1
    furnished: bool = False
    pets_permitted: bool = False
    term_type: str = "fixed"  # fixed | month_to_month

    def parsed_start(self) -> Optional[date]:
        return _parse_iso(self.start_date)

    def parsed_end(self) -> Optional[date]:
        return _parse_iso(self.end_date)


def _parse_iso(value: str) -> Optional[date]:
    try:
        return date.fromisoformat(str(value).strip())
    except (ValueError, AttributeError):
        return None


@dataclass
class LeasePackRequest:
    """Everything needed to assemble one lease + disclosure pack for one
    property in one jurisdiction."""

    pack_id: str
    jurisdiction: str  # e.g. "US-CA" — resolved against jurisdictions/*.yaml
    property: Property
    tenancy: Tenancy
    landlord: Party
    tenants: list[Party] = field(default_factory=list)
    agent: Optional[Party] = None
    disclosure_facts: dict[str, Any] = field(default_factory=dict)
    """Jurisdiction-specific answers, keyed by the fact names rules reference.
    Absent key means unanswered, which is never read as "no"."""

    def lookup_fact(self, name: str) -> Any:
        """Resolve a fact name to a value, or `UNSET` if it was never supplied.

        Typed `Property` and `Tenancy` attributes are visible to rules under
        their own names, so a rule can say `year_built < 1978` without the fact
        having to be duplicated into `disclosure_facts`. An explicit entry in
        `disclosure_facts` wins, which lets an example override a derived value
        without editing the typed record.
        """
        if name in self.disclosure_facts:
            value = self.disclosure_facts[name]
            return UNSET if value is None else value

        # `state`, `year_built`, `units_in_building`, `monthly_rent` and the rest
        # are reachable here under their own names, so a rule can test them
        # without the fact being duplicated into `disclosure_facts`.
        for source in (self.property, self.tenancy):
            if hasattr(source, name):
                value = getattr(source, name)
                return UNSET if value is None else value

        return UNSET

    def all_tenant_names(self) -> str:
        return ", ".join(t.name for t in self.tenants) if self.tenants else ""
